logging:
  level:
    com:
      skynill:
        timetracker: DEBUG
    org:
      springframework:
        retry: DEBUG
      hibernate:
        SQL: WARN
    liquibase: WARN

spring:
  jpa:
    hibernate:
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
